#!/bin/sh

if [ "$1" = "service" ]
then
args=("$@")
lamp executeScript --name ogCreateAlert.groovy  -Dentity="${args[0]}" -DnotificationType="${args[1]}" -DserviceState="${args[2]}" -DlongDateTime="${args[3]}" -DserviceDesc="${args[4]}" -DserviceOutput="${args[5]}" -DserviceGroupName="${args[6]}" -DlastServiceCheck="${args[7]}" -DlastServiceStateChange="${args[8]}" -DserviceDuration="${args[9]}" -DserviceAttempt="${args[10]}" -DmaxServiceAttempts="${args[11]}" -DserviceStateType="${args[12]}" -DserviceLatency="${args[13]}" -DhostName="${args[14]}" -DhostAlias="${args[15]}" -DhostAddress="${args[16]}" -DhostDuration="${args[17]}" -DhostStateType="${args[18]}"
else
args=("$@")
lamp executeScript --name ogCreateAlert.groovy -Dentity="${args[0]}" -DnotificationType="${args[1]}" -DlongDateTime="${args[2]}" -DserviceDuration="${args[3]}" -DserviceStateType="${args[4]}" -DhostName="${args[5]}" -DhostGroupName="${args[6]}" -DhostState="${args[7]}" -DlastHostCheck="${args[8]}" -DlastHostStateChange="${args[9]}" -DhostAlias="${args[10]}" -DhostAddress="${args[11]}" -DhostDuration="${args[12]}" -DhostOutput="${args[13]}" -DhostAttempt="${args[14]}" -DmaxHostAttempts="${args[15]}" -DhostStateType="${args[16]}" -DhostLatency="${args[17]}"
fi
