#!/bin/sh

# Specify the location of your JAVA path main folder
export JAVA_HOME=/usr/lib/jvm/jre-1.x.x

# Specify the location of the lamp utility
LAMP_HOME=/usr/local/lamp

$LAMP_HOME/lamp executeScript --name ogCreateAlert.groovy -Dentity="$1"



