#!/bin/sh

# Specify the location of the lamp utility
LAMP_HOME=/opt/lamp

SUBJECT="$1"
TEXT_MESSAGE="$2"
NODEID="$3"

$LAMP_HOME/lamp executeScript --name ogCreateAlert.groovy -Dsubject="$SUBJECT" -DtextMessage="$TEXT_MESSAGE" -DnodeId="$NODEID"



